version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo installing AWS SAM
      - pip3 install --upgrade pip
      - pip3 install --upgrade --force-reinstall aws-sam-cli
      - sam --version
  build:
    commands:
      - set -e
      - echo "Building with AWS SAM"
      - sam --version
      - sam build --use-container --debug --parallel

  post_build:
    commands:
      - echo "Deploying the stack"
      - sam deploy --stack-name datapipeline --resolve-image-repos --resolve-s3 --force-upload --no-fail-on-empty-changeset --no-confirm-changeset